export default {
    AppBootstrap: 'app:bootstrap',
    AppearanceChanged: 'appearance-changed',
    AppInitialised: 'app:initialised',
    AuthorizationFailed: 'authorization-failed',
    CountryChanged: 'country-changed',
    CurrencyChanged: 'currency-changed',
    LanguageChanged: 'language-changed',
    PreferencesChanged: 'preferences-changed',
    SessionCreated: 'session-created',
    SessionDestroyed: 'session-destroyed',
    SessionInitialized: 'session-initialized',
    SessionMounted: 'session-mounted',
    SessionRefreshed: 'session-refreshed',
    SoundActivated: 'sound-activated',
    SoundMuted: 'sound-muted',
    TimeZoneChanged: 'timezone-changed',
    TokenMismatched: 'token-mismatched',
    UserAuthenticated: 'user-authenticated',
    UserChanged: 'user-changed',
    UserMounted: 'user-mounted',
    UserSignedOut: 'user-signed-out',
    UserUnmounted: 'user-unmounted',
    WalletChanged: 'wallet-changed',
    WalletExpired: 'wallet-expired',
}