export default {
    AppBootstrap: 'app:bootstrap',
    AppInitialised: 'app:initialised',
    UserUpdated: 'user-updated',
    UserMounted: 'user-mounted',
    UserUnmounted: 'user-unmounted',
    SessionInitialized: 'session-initialized',
    AuthorizationRejected: 'authorization-rejected',
    Unauthorized: 'authentication-failed',
    SessionCreated: 'session-created',
    SessionMounted: 'session-mounted',
    SessionRefreshed: 'session-refreshed',
    SessionInvalidated: 'session-invalidated',
    SessionDestroyed: 'session-destroyed',
    UserAuthenticated: 'user-authenticated',
    UserSignedOut: 'user-signed-out',
    WalletChanged: 'wallet-changed',
    CurrencyChanged: 'currency-changed',
    CountryChanged: 'country-changed',
    TimeZoneChanged: 'timezone-changed',
    SoundMuted: 'sound-muted',
    SoundActivated: 'sound-activated',
    LanguageChanged: 'language-changed',
    PreferencesChanged: 'preferences-changed',
}